import { VISUAL_MASTER_PROMPT_VERSION } from "@/lib/visual-concept/config";
import { directVisualMaster, type MasterArtDirectionBrief } from "@/lib/visual-concept/master-art-director";
import type { VisualBrief } from "@/lib/visual-concept/types";

const SECTIONS = [
  "01 HERO",
  "02 OVERVIEW",
  "03 FEATURE / VALUE STORY",
  "04 VISUAL STORY / EDITORIAL PAUSE",
  "05 USAGE",
  "06 RETURN POLICY",
  "07 DECISION / CTA",
  "08 FAQ",
  "09 FOOTER / DISCLOSURE",
];

export function buildVisualMasterPrompt(brief: VisualBrief, artDirection?: MasterArtDirectionBrief): string {
  const art = artDirection ?? directVisualMaster(brief);
  const copy = brief.allowedCopy.length ? brief.allowedCopy.map((line) => `- ${line}`).join("\n") : "- none";
  return [
    "VISUAL MASTER",
    "Create one coherent long-form desktop website design reference.",
    "This is a single visual system, not three layouts placed in sequence.",
    "It is not HTML, not consumer evidence, and not publication approval.",
    "",
    "OUTPUT FORM",
    "FULL-PAGE PREMIUM ECOMMERCE / DTC LANDING PAGE WEBSITE DESIGN MOCKUP",
    "High-end direct-to-consumer ecommerce, premium editorial commerce, and a clear conversion hierarchy.",
    "The artifact must look like a screenshot of a professionally art-directed brand website.",
    "It must contain the regions below and appear scrollable beyond one viewport.",
    "It must not look like an advertisement, a poster, a social-media creative, an infographic, an Amazon listing, a SaaS template, a Tailwind demo, a cheap advertorial, or a repeated card grid.",
    "",
    "WEBSITE REGIONS",
    "These regions are visual only. They do not authorize new facts.",
    ...SECTIONS,
    "",
    "SYNTHESIZED ART DIRECTION",
    `Direction: ${art.masterDirection}`,
    `Visual language: ${art.baseVisualLanguage}. Product staging language: ${art.productLanguage}. Information hierarchy: ${art.conversionLanguage}.`,
    `Hero: ${art.heroStrategy}`,
    `Typography: ${art.typographyCharacter}`,
    `Photography: ${art.photographicLanguage}`,
    `Materials: ${art.materialVocabulary.join(", ")}.`,
    `Depth: ${art.depthStrategy}`,
    `Whitespace: ${art.whitespaceStrategy}`,
    `Narrative: ${art.visualNarrative}`,
    "Section rhythm:",
    ...art.sectionChoreography,
    `Product stage: ${art.productStaging}`,
    `CTA: ${art.ctaVisualStrategy}`,
    `FAQ: ${art.faqVisualStrategy}`,
    `Avoid: ${art.avoidPatterns.join(", ")}.`,
    "This art direction is not evidence and must not create consumer claims.",
    art.visualContext === "unspecified"
      ? "No visual atmosphere was inferred. Do not invent a product category."
      : `Atmosphere only: ${art.visualContext}. Do not turn this atmosphere into a consumer claim, benefit, or category statement.`,
    "",
    "PRODUCT IDENTITY",
    brief.productIdentity.name || "Unnamed product",
    "The original product asset remains authoritative for product identity.",
    "Do not redesign the product label, brand logo, packaging text, or package geometry.",
    "Do not generate a substitute package.",
    "Leave one blank product stage in the upper area of the hero, about one fifth of the page width, integrated into the scene.",
    "Do not draw a bottle, label, person, icon, or badge on that stage. The original asset is placed there after generation.",
    "The source asset may already contain a person and external promotional graphics fused with the product.",
    "Do not remove, inpaint, or reconstruct that person or those graphics.",
    "Do not reproduce or amplify that person, those icons, or that text anywhere else on the page.",
    "Do not make the source asset an enormous dominant hero object. Premium character comes from composition, photography, material, type, depth, whitespace, and section rhythm.",
    "",
    "PERMITTED CONSUMER COPY",
    "Only the following allowedCopy may be intentionally requested as consumer copy.",
    copy,
    "DO NOT CREATE NEW HEADLINES, SLOGANS, BENEFITS, RESULTS, TESTIMONIALS, RATINGS, PRICES, DISCOUNTS, CERTIFICATIONS, DOCTOR RECOMMENDATIONS, MEDICAL CLAIMS, SCIENTIFIC CLAIMS, SCARCITY, OR GUARANTEES.",
    "If a return policy appears in allowedCopy, render that meaning only.",
    "Do not rewrite a return policy as a guarantee, a risk-free promise, or a money-back promise.",
    "FAQ questions may only be questions already present in allowedCopy. Do not invent questions.",
    "If accurate text rendering is difficult, use neutral restrained typographic placeholders.",
    "Do not invent substitute marketing language.",
    "Generated image text is not authoritative.",
    "",
    "PEOPLE",
    "Do not intentionally generate a doctor, a customer testimonial, a before-and-after, an endorsement figure, or a person using the product to imply a result.",
    "",
    "OUTPUT INTENT",
    "Design reference only.",
    `promptVersion=${VISUAL_MASTER_PROMPT_VERSION}`,
    `contentVersion=${brief.contentVersion}`,
  ].join("\n");
}
