export const PRIMARY_SOURCE_TIMEOUT_MS = 10_000;
export const SEARCH_PROVIDER_TIMEOUT_MS = 10_000;
export const PER_ALTERNATIVE_SOURCE_TIMEOUT_MS = 8_000;
export const MAX_ALTERNATIVE_SOURCE_FETCHES = 5;
export const GLOBAL_SOURCE_RESOLUTION_TIMEOUT_MS = 45_000;
export const ALTERNATIVE_FETCH_CONCURRENCY = 3;
export const ROBOTS_CHECK_TIMEOUT_MS = 5_000;
