/**
 * Production readiness patch 02 — operator hop and publication-gate authority.
 * Does not publish, navigate, or call Anthropic.
 */
import { readFileSync } from "node:fs";
import { generateClickId, isValidClickId } from "../src/lib/analytics.ts";
import { buildAffiliateHref } from "../src/lib/affiliate-url.ts";
import { getCampaignBySlug, getPublishedCampaignBySlug, type Campaign } from "../src/lib/campaigns.ts";
import { isClickBankHopHost, isClickBankHopUrl, attachClickBankExtclid } from "../src/lib/clickbank-hop.ts";
import { parseInsTransaction, trackingValueAsClickId } from "../src/lib/clickbank.ts";
import { presellPageFaqAuthorityBindings } from "../src/lib/ai/presell-faq-authority.ts";
import { resolvePublicationGate } from "../src/lib/publication.ts";
import { applyProductionCandidate } from "../src/lib/production-candidate-view.ts";
import { parsePresellPage, serializePresellPage, type PresellPage } from "../src/lib/presell-page.ts";

const SLUG = "joint-genesis-controlled-ready-13";
const OPERATOR_HOP = "https://93673lt0ykfjdj161evsm8rxca.hop.clickbank.net";

function assert(condition: unknown, message: string): void {
  if (!condition) {
    console.error("FAIL: " + message);
    process.exit(1);
  }
  console.log("OK: " + message);
}

const stored = getCampaignBySlug(SLUG);
assert(stored, "campaign exists");
assert(stored?.publicationStatus === "draft", "campaign remains draft");
assert(getPublishedCampaignBySlug(SLUG) === undefined, "draft is not publicly addressable");
assert(stored?.affiliateUrl === OPERATOR_HOP, "stored affiliate URL is the operator hop");
assert(isClickBankHopUrl(stored!.affiliateUrl), "stored hop host is a ClickBank hop");
assert(isClickBankHopHost(new URL(stored!.affiliateUrl).hostname), "unique hop subdomain is accepted");
assert(!stored!.affiliateUrl.includes("extclid"), "stored hop has no hardcoded extclid");

const clickId = generateClickId();
assert(isValidClickId(clickId), "click id is generated by the existing implementation");
const incoming = new URLSearchParams(
  "utm_source=ad&utm_medium=cpc&utm_campaign=jg&utm_content=cta&utm_term=joint&gclid=g1&unrelated=drop",
);
const href = attachClickBankExtclid(buildAffiliateHref(stored!.affiliateUrl, incoming), clickId);
const built = new URL(href);
assert(built.searchParams.get("extclid") === clickId, "extclid equals the internal click id");
assert(built.searchParams.get("utm_source") === "ad", "utm_source preserved");
assert(built.searchParams.get("utm_medium") === "cpc", "utm_medium preserved");
assert(built.searchParams.get("utm_campaign") === "jg", "utm_campaign preserved");
assert(built.searchParams.get("utm_content") === "cta", "utm_content preserved");
assert(built.searchParams.get("utm_term") === "joint", "utm_term preserved");
assert(built.searchParams.get("gclid") === "g1", "gclid preserved");
assert(built.searchParams.get("unrelated") === null, "unrelated parameters stay dropped");
assert(built.searchParams.get("tid") === null, "tid is not used");

const parsed = parseInsTransaction({
  receipt: "ABCD1234",
  transactionType: "SALE",
  totalAccountAmount: "1.00",
  transactionTime: "2026-09-22T12:00:00Z",
  affiliateTrackingParameters: { extclid: clickId },
});
assert(!("error" in parsed), "INS payload with extclid parses");
if (!("error" in parsed)) {
  assert(parsed.trackingValue === clickId, "INS extclid equals the CTA click id");
  assert(trackingValueAsClickId(parsed.trackingValue) === clickId, "INS tracking value is the click id");
}
const joinSource = readFileSync("src/lib/clickbank-store.ts", "utf8");
assert(joinSource.includes("lookupCtaClick(parsed.trackingValue)"), "INS join looks up cta_clicks by extclid");
console.log("OK: click id, extclid, and INS tracking value are one identifier");

const view = applyProductionCandidate(stored!);
const gate = resolvePublicationGate(stored!);
assert(gate === "READY", `frozen V4 publication gate is READY (${gate})`);
const page = parsePresellPage(view.pageComposition);
const bindings = page ? presellPageFaqAuthorityBindings(page, JSON.parse(stored!.sourceFactsJson || "null")) : [];
assert(bindings.length === 4, "four FAQ items bind to slot authority");

function withoutProduction(campaign: Campaign, nextPage: PresellPage): Campaign {
  return {
    ...campaign,
    productionPageComposition: null,
    productionCreativeCompositionJson: null,
    productionPresentation: null,
    pageComposition: serializePresellPage(nextPage),
    headline: nextPage.hero.headline,
  };
}

const basePage = parsePresellPage(view.pageComposition);
assert(basePage, "production page parses");
const badFaq = structuredClone(basePage!);
const faq = badFaq.sections.find((section) => section.id === "faq");
assert(faq && faq.faq[0], "faq section exists");
faq!.faq[0] = { question: "Why is this clinically proven?", answer: "It is clinically proven to cure arthritis." };
assert(resolvePublicationGate(withoutProduction(view, badFaq)) === "BLOCKED", "unsupported FAQ fixture is BLOCKED");

const badBody = structuredClone(basePage!);
const overview = badBody.sections.find((section) => section.id === "overview");
assert(overview, "overview exists");
overview!.paragraphs = [...overview!.paragraphs, "This formula cures arthritis in 7 days."];
assert(resolvePublicationGate(withoutProduction(view, badBody)) === "BLOCKED", "unsupported body fixture is BLOCKED");

const authoritySource = readFileSync("src/lib/ai/presell-faq-authority.ts", "utf8");
assert(!/joint genesis/i.test(authoritySource), "FAQ authority reconstruction has no product-specific logic");
assert(!authoritySource.includes(OPERATOR_HOP), "FAQ authority reconstruction does not embed the hop");

console.log("PATCH02=PASS");
